# Color codes:
# Dark red §4
# Red §c
# Gold §6
# Yellow §e
# Dark Green §2
# Green §a
# Aqua §b
# Dark Aqua §3
# Dark Blue §1
# Blue §9
# Light Purple §d
# Purple §5
# White §f
# Gray §7
# Dark Gray §8
# Black §0

# Format codes:
# Obfuscated §k
# Bold §l
# Strikethrough §m
# Underline §n
# Italic §o
# Reset §r

maxPlayers: 0
motds:
  - §a§lDefault MOTD 1
  - §c§nDefault MOTD 2